// Code generated by protoc-gen-go. DO NOT EDIT.
// source: person.proto

package main

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Job struct {
	Title                string   `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Salary               float32  `protobuf:"fixed32,2,opt,name=salary,proto3" json:"salary,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Job) Reset()         { *m = Job{} }
func (m *Job) String() string { return proto.CompactTextString(m) }
func (*Job) ProtoMessage()    {}
func (*Job) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c9e10cf24b1156d, []int{0}
}

func (m *Job) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Job.Unmarshal(m, b)
}
func (m *Job) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Job.Marshal(b, m, deterministic)
}
func (m *Job) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Job.Merge(m, src)
}
func (m *Job) XXX_Size() int {
	return xxx_messageInfo_Job.Size(m)
}
func (m *Job) XXX_DiscardUnknown() {
	xxx_messageInfo_Job.DiscardUnknown(m)
}

var xxx_messageInfo_Job proto.InternalMessageInfo

func (m *Job) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Job) GetSalary() float32 {
	if m != nil {
		return m.Salary
	}
	return 0
}

type Person struct {
	Firstname            string    `protobuf:"bytes,1,opt,name=firstname,proto3" json:"firstname,omitempty"`
	Lastname             string    `protobuf:"bytes,2,opt,name=lastname,proto3" json:"lastname,omitempty"`
	Age                  int32     `protobuf:"varint,3,opt,name=age,proto3" json:"age,omitempty"`
	Job                  *Job      `protobuf:"bytes,4,opt,name=job,proto3" json:"job,omitempty"`
	Friends              []*Person `protobuf:"bytes,5,rep,name=friends,proto3" json:"friends,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Person) Reset()         { *m = Person{} }
func (m *Person) String() string { return proto.CompactTextString(m) }
func (*Person) ProtoMessage()    {}
func (*Person) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c9e10cf24b1156d, []int{1}
}

func (m *Person) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Person.Unmarshal(m, b)
}
func (m *Person) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Person.Marshal(b, m, deterministic)
}
func (m *Person) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Person.Merge(m, src)
}
func (m *Person) XXX_Size() int {
	return xxx_messageInfo_Person.Size(m)
}
func (m *Person) XXX_DiscardUnknown() {
	xxx_messageInfo_Person.DiscardUnknown(m)
}

var xxx_messageInfo_Person proto.InternalMessageInfo

func (m *Person) GetFirstname() string {
	if m != nil {
		return m.Firstname
	}
	return ""
}

func (m *Person) GetLastname() string {
	if m != nil {
		return m.Lastname
	}
	return ""
}

func (m *Person) GetAge() int32 {
	if m != nil {
		return m.Age
	}
	return 0
}

func (m *Person) GetJob() *Job {
	if m != nil {
		return m.Job
	}
	return nil
}

func (m *Person) GetFriends() []*Person {
	if m != nil {
		return m.Friends
	}
	return nil
}

func init() {
	proto.RegisterType((*Job)(nil), "main.Job")
	proto.RegisterType((*Person)(nil), "main.Person")
}

func init() {
	proto.RegisterFile("person.proto", fileDescriptor_4c9e10cf24b1156d)
}

var fileDescriptor_4c9e10cf24b1156d = []byte{
	// 194 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x44, 0x8f, 0x4d, 0x6e, 0x86, 0x20,
	0x10, 0x86, 0x83, 0xa8, 0xad, 0xa3, 0x8b, 0x66, 0xd2, 0x34, 0xa4, 0xed, 0x82, 0xb8, 0x68, 0x58,
	0xb9, 0xd0, 0x5b, 0xb8, 0x6a, 0xb8, 0x01, 0xa4, 0xd8, 0xd0, 0x28, 0x18, 0x60, 0xd3, 0xa3, 0xf4,
	0xb6, 0x8d, 0x7f, 0xdf, 0xb7, 0xe3, 0x79, 0x1f, 0x66, 0xf2, 0x0e, 0x34, 0xab, 0x09, 0xd1, 0xbb,
	0x6e, 0x0d, 0x3e, 0x79, 0xcc, 0x17, 0x65, 0x5d, 0x3b, 0x00, 0x1d, 0xbd, 0xc6, 0x67, 0x28, 0x92,
	0x4d, 0xb3, 0x61, 0x84, 0x13, 0x51, 0xc9, 0x03, 0xf0, 0x05, 0xca, 0xa8, 0x66, 0x15, 0x7e, 0x59,
	0xc6, 0x89, 0xc8, 0xe4, 0x49, 0xed, 0x1f, 0x81, 0xf2, 0x73, 0xdf, 0x85, 0xef, 0x50, 0x4d, 0x36,
	0xc4, 0xe4, 0xd4, 0x72, 0x0d, 0xdf, 0x03, 0x7c, 0x85, 0xc7, 0x59, 0x9d, 0x32, 0xdb, 0xe5, 0x8d,
	0xf1, 0x09, 0xa8, 0xfa, 0x36, 0x8c, 0x72, 0x22, 0x0a, 0xb9, 0x3d, 0xf1, 0x0d, 0xe8, 0x8f, 0xd7,
	0x2c, 0xe7, 0x44, 0xd4, 0x7d, 0xd5, 0x6d, 0xfd, 0xba, 0xd1, 0x6b, 0xb9, 0xa5, 0xf8, 0x01, 0x0f,
	0x53, 0xb0, 0xc6, 0x7d, 0x45, 0x56, 0x70, 0x2a, 0xea, 0xbe, 0x39, 0x3e, 0x1c, 0x3d, 0xe4, 0x25,
	0x75, 0xb9, 0x5f, 0x37, 0xfc, 0x07, 0x00, 0x00, 0xff, 0xff, 0x3d, 0x53, 0xd5, 0x27, 0xed, 0x00,
	0x00, 0x00,
}
